#!/usr/bin/env bash
# Rack Dashboard — onboarding.
#
# Asks for each host in your rack, writes config/services.yaml, and starts the
# dashboard. It NEVER touches your other machines: it prints the one command to
# run on each, so nothing is installed behind your back.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RESET=$'\033[0m'
say()  { printf '%s\n' "$*"; }
head2() { printf '\n%s%s%s\n' "$BOLD" "$*" "$RESET"; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '  %s!%s %s\n' "$YELLOW" "$RESET" "$*"; }

command -v docker >/dev/null || { say "Docker is required on this host. Install it first."; exit 1; }
docker compose version >/dev/null 2>&1 || { say "Docker Compose v2 is required."; exit 1; }

head2 "Rack Dashboard setup"
say "${DIM}One pane for every machine in your rack. Ctrl-C to abort.${RESET}"

# ---------------------------------------------------------------- dashboard host
head2 "1. This machine"
read -rp "  Address other devices reach it on [192.168.1.10]: " SELF_ADDR
SELF_ADDR="${SELF_ADDR:-192.168.1.10}"
read -rp "  A name for it [dashboard]: " SELF_NAME
SELF_NAME="${SELF_NAME:-dashboard}"

# ---------------------------------------------------------------- other hosts
head2 "2. The other machines"
say "${DIM}Blank name when you are done.${RESET}"
HOSTS=("$SELF_NAME|127.0.0.1|self")
AGENT_DOCKER=(); AGENT_PKG=()
while :; do
  read -rp "  Host name (blank to finish): " HN
  [ -z "$HN" ] && break
  read -rp "    Address for $HN: " HA
  [ -z "$HA" ] && { warn "no address, skipped"; continue; }
  read -rp "    Does $HN run Docker? [Y/n]: " HD
  case "${HD:-Y}" in
    [Nn]*) HOSTS+=("$HN|$HA|pkg");    AGENT_PKG+=("$HN ($HA)") ;;
    *)     HOSTS+=("$HN|$HA|docker"); AGENT_DOCKER+=("$HN ($HA)") ;;
  esac
done

# ---------------------------------------------------------------- alerts
head2 "3. Alerts (optional)"
read -rp "  Do you already run Alertmanager? [y/N]: " HAS_AM
ALERT_URL=""
case "${HAS_AM:-N}" in
  [Yy]*) read -rp "    Alertmanager URL [http://127.0.0.1:9093]: " ALERT_URL
         ALERT_URL="${ALERT_URL:-http://127.0.0.1:9093}" ;;
esac

# ---------------------------------------------------------------- generate
head2 "4. Writing config"
mkdir -p config
{
  echo "# Generated by setup.sh. Safe to edit and commit — it holds no secrets."
  echo "# Reference API keys as {{HOMEPAGE_VAR_NAME}} and put the values in .env."
  echo
  echo "- Performance:"
  if [ -n "$ALERT_URL" ]; then
    cat <<YAML
    - Latest alerts:
        icon: mdi-bell-alert
        description: 3 most recent
        widget:
          type: customapi
          url: ${ALERT_URL}/api/v2/alerts?active=true&silenced=false&inhibited=false
          method: GET
          mappings:
            - field: "0.labels.alertname"
              label: Latest
            - field: "1.labels.alertname"
              label: 2nd
            - field: "2.labels.alertname"
              label: 3rd
YAML
  fi
  for entry in "${HOSTS[@]}"; do
    IFS='|' read -r n a _k <<<"$entry"
    cat <<YAML
    - ${n}:
        icon: mdi-server
        description: cpu / ram / load
        widget:
          type: glances
          url: http://${a}:61208
          version: 4
          metric: info
    - ${n} — activity:
        icon: mdi-chart-line
        description: what is burning it
        widget:
          type: glances
          url: http://${a}:61208
          version: 4
          metric: process
YAML
  done
  echo
  echo "# Add your own services below. Homepage ships widgets for ~100 apps."
  echo "- Services:"
  echo "    - Example:"
  echo "        icon: mdi-application"
  echo "        href: http://${SELF_ADDR}"
  echo "        description: replace me"
} > config/services.yaml
ok "config/services.yaml — ${#HOSTS[@]} hosts"

[ -f .env ] || { sed "s|192.168.1.10:3080|${SELF_ADDR}:3080|" .env.example > .env; ok ".env created from .env.example"; }

# ---------------------------------------------------------------- agents
if [ ${#AGENT_DOCKER[@]} -gt 0 ] || [ ${#AGENT_PKG[@]} -gt 0 ]; then
  head2 "5. Run this on each monitored host"
  say "${DIM}Nothing was installed on them. These are yours to run.${RESET}"
  if [ ${#AGENT_DOCKER[@]} -gt 0 ]; then
    printf '\n  With Docker — %s:\n' "$(IFS=, ; echo "${AGENT_DOCKER[*]}")"
    say "    mkdir -p ~/rack-dashboard-agent && cd ~/rack-dashboard-agent"
    say "    curl -fsSLO https://raw.githubusercontent.com/OWNER/rack-dashboard/main/agent/docker-compose.yml"
    say "    docker compose up -d"
  fi
  if [ ${#AGENT_PKG[@]} -gt 0 ]; then
    printf '\n  Without Docker — %s:\n' "$(IFS=, ; echo "${AGENT_PKG[*]}")"
    say "    sudo apt-get install -y glances"
    say "    sudo curl -fsSL -o /etc/systemd/system/glances-web.service \\"
    say "         https://raw.githubusercontent.com/OWNER/rack-dashboard/main/agent/glances-web.service"
    say "    sudo systemctl daemon-reload && sudo systemctl enable --now glances-web"
  fi
  printf '\n'
  warn "Glances has NO authentication. Keep :61208 on your LAN or VPN."
fi

head2 "6. Starting the dashboard"
docker compose up -d
sleep 6
if curl -fsS -m 8 "http://127.0.0.1:3080/api/healthcheck" >/dev/null 2>&1; then
  ok "up at http://${SELF_ADDR}:3080"
else
  warn "not answering yet — 'docker compose logs homepage' to see why"
fi

head2 "Done"
say "  Hosts whose agent is not running yet will show an error badge. That is expected"
say "  until you run the commands above on them."
